/**
 * Text-to-Speech (TTS) Service
 * Model: gemini-3.8-flash-lite-tts
 * Default Voice: Puck
 * Synthesizes interviewer question text into audio for playback.
 */

const { getAiServiceUrl } = require('../config/aiServiceConfig');
const AI_SERVICE_URL = getAiServiceUrl();

class TextToSpeechService {
  constructor() {
    this.modelName = process.env.TTS_MODEL || 'gemini-3.8-flash-lite-tts';
    this.defaultVoice = process.env.TTS_VOICE || 'Puck';
  }

  /**
   * Generates audio for interview question text.
   * @param {Object} params
   * @param {string} params.text - The exact question text generated by Interview Agent
   * @param {string} [params.voice] - Prebuilt voice name (e.g. Puck, Aoede, Charon)
   * @returns {Promise<{success: boolean, audioUrl?: string, error?: string, latencyMs?: number, cached?: boolean}>}
   */
  async generateSpeech({ text, voice }) {
    const startTime = Date.now();
    const cleanText = (text || '').trim();

    if (!cleanText) {
      console.warn('[TextToSpeechService] [ERROR] Cannot synthesize empty text.');
      return { success: false, error: 'EMPTY_TEXT', message: 'No text provided for audio synthesis.' };
    }

    const chosenVoice = voice || this.defaultVoice;
    console.log(`[TTS_STARTED] model=${this.modelName}, voice=${chosenVoice}, text_length=${cleanText.length}`);

    try {
      const response = await fetch(`${AI_SERVICE_URL}/voice/synthesize`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          text: cleanText,
          voice: chosenVoice,
          format: 'json',
        }),
        signal: AbortSignal.timeout(35000),
      });

      const totalLatency = Date.now() - startTime;

      if (!response.ok) {
        const errorText = await response.text();
        console.error(`[TextToSpeechService] [ERROR] AI Service TTS failed status ${response.status}:`, errorText.slice(0, 200));
        return {
          success: false,
          error: 'TTS_FAILED',
          message: 'Audio synthesis failed. Text fallback will be used.',
          latencyMs: totalLatency,
        };
      }

      const result = await response.json();
      console.log(`[TTS_COMPLETED] Audio generated in ${totalLatency}ms (cached: ${result.cached})`);

      return {
        success: true,
        audioUrl: result.audioUrl,
        voice: result.voice || chosenVoice,
        model: result.model || this.modelName,
        cached: Boolean(result.cached),
        latencyMs: totalLatency,
      };
    } catch (err) {
      const totalLatency = Date.now() - startTime;
      console.error('[TextToSpeechService] [ERROR] TTS request failed:', err.message);
      return {
        success: false,
        error: err.name === 'TimeoutError' ? 'TTS_TIMEOUT' : 'TTS_FAILED',
        message: 'Could not generate interviewer audio.',
        latencyMs: totalLatency,
      };
    }
  }
}

module.exports = new TextToSpeechService();
