// Shared option lists for profile setup and the profile page
export const EXPERIENCE_LEVELS = ['Beginner', 'Intermediate', 'Experienced']

export const FIELD_OPTIONS = [
  'Software Engineering',
  'Computer Science',
  'Information Technology',
  'Data Science',
  'Artificial Intelligence / Machine Learning',
  'Cyber Security',
  'Network Engineering',
  'Cloud Computing',
  'DevOps',
  'UI/UX Design',
  'Quality Assurance / Software Testing',
  'Business Information Systems',
  'Business Management',
  'Accounting & Finance',
  'Marketing',
  'Human Resource Management',
  'Engineering',
  'Healthcare',
  'Education',
  'Other',
]

export const CAREER_STAGE_OPTIONS = [
  'Student / Undergraduate',
  'Recent Graduate',
]

export const POPULAR_SKILLS = [
  'React',
  'JavaScript',
  'TypeScript',
  'Node.js',
  'Python',
  'Java',
  'C++',
  'C#',
  'HTML5',
  'CSS3',
  'Next.js',
  'Vue.js',
  'Angular',
  'Express',
  'Django',
  'Flask',
  'FastAPI',
  'Spring Boot',
  'SQL',
  'PostgreSQL',
  'MySQL',
  'MongoDB',
  'Redis',
  'Docker',
  'Kubernetes',
  'AWS',
  'Google Cloud',
  'Azure',
  'Git',
  'Linux',
  'REST APIs',
  'GraphQL',
  'Microservices',
  'Machine Learning',
  'Deep Learning',
  'PyTorch',
  'TensorFlow',
  'Data Science',
  'Pandas',
  'NumPy',
  'UI/UX Design',
  'Figma',
  'CI/CD',
  'Cyber Security',
  'Network Engineering',
  'Agile / Scrum',
  'System Design',
  'Testing & QA',
  'Go',
  'Rust',
  'Swift',
  'Kotlin',
  'Flutter',
]
